shinyUI(fluidPage(
  fluidRow(
    column(4,
           wellPanel(
             analysisUI('analysis'),
             plotOptionsUI('plotOptions')
           )),
    column(8,
           screeUI('scree'))
  )
))
